[colors]
brights = [
    '#62686c',
    '#DED1D8',
    '#73ffd8',
    '#fcf4ad',
    '#378dfe',
    '#ae81ff',
    '#CA2DA0',
    '#5ffbbe',
]
ansi = [
    '#0b3b61',
    '#ff3a3a',
    '#52ffcf',
    '#fff383',
    '#1376f8',
    '#c792ea',
    '#5DFF60',
    '#15fca2',
]
background = '#010b17'
cursor_bg = '#38ff9c'
cursor_border = '#bbbbbb'
cursor_fg = '#ffffff'
foreground = '#ebddf4'
selection_bg = '#b5d5ff'
selection_fg = '#000000'

[colors.indexed]

[metadata]
name = 'coolnight'
origin_url = 'https://gihub.com'

